name: Deploy to GitHub Pages

# Run workflow on every push to the master branch
on:
  push:
    branches: [ master ]

jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    # uses GitHub's checkout action to checkout code form the master branch
    - uses: actions/checkout@v3
    
    # sets up .NET Core SDK
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.*

    # publishes Blazor project to the release-folder
    - name: Publish .NET Core Project
      run: dotnet publish EnglishChallengesWebApp.csproj -c Release -o release --nologo
    
    # changes the base-tag in index.html from '/' to 'EnglishChallengesWebApp' to match GitHub Pages repository subdirectory
    - name: Change base-tag in index.html from / to EnglishChallengesWebApp
      run: sed -i 's/<base href="\/" \/>/<base href="\/EnglishChallengesWebApp\/" \/>/g' release/wwwroot/index.html
    
    # copy index.html to 404.html to serve the same file when a file is not found
    - name: copy index.html to 404.html
      run: cp release/wwwroot/index.html release/wwwroot/404.html

    # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
      
    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v1.2.4
      with:
        # Should this action only emit build telemetry instead of deploying the build artifact?
        emit_telemetry: # optional, default is false
        # The status of the previous build.
        conclusion: # optional
        # GitHub token
        token: # default is ${{ github.token }}
        # Time in milliseconds after which to timeout and cancel the deployment (default: 10 minutes)
        timeout: # optional, default is 600000
        # Maximum number of status report errors before cancelling a deployment (default: 10)
        error_count: # optional, default is 10
        # Time in milliseconds between two deployment status report (default: 5 seconds)
        reporting_interval: # optional, default is 5000
        # Name of the artifact to deploy
        artifact_name: # optional, default is github-pages
        # Is this attempting to deploy a pull request as a GitHub Pages preview site? (NOTE: This feature is only in alpha currently and is not available to the public!)
        preview: # optional, default is false
